# Generated by Django 4.1 on 2022-08-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=50)),
                ('gpu', models.CharField(max_length=50)),
                ('motherboard', models.CharField(max_length=50)),
            ],
        ),
    ]
